INSERT INTO PRODUTO(DESCRICAO, VALOR) values('ARROZ', 20.00), ('TOMATE', 4.0), ('LEITE', 5.0);

INSERT INTO pessoa (tipo, nome, cpf) VALUES('F','MARIA', '123');
INSERT INTO pessoa (tipo, nome, cnpj) VALUES('J','IFTO', '345');

INSERT INTO VENDA(DATA, PESSOA_ID) values (CURRENT_TIMESTAMP, 1);
INSERT INTO VENDA(DATA, PESSOA_ID) values (CURRENT_TIMESTAMP, 2);
INSERT INTO VENDA(DATA, PESSOA_ID) values (CURRENT_TIMESTAMP, 1);

INSERT INTO ITEM_VENDA(QUANTIDADE, PRODUTO_ID, VENDA_ID) values (2.0, 2, 1);
INSERT INTO ITEM_VENDA(QUANTIDADE, PRODUTO_ID, VENDA_ID) values (4.0, 1, 2);
INSERT INTO ITEM_VENDA(QUANTIDADE, PRODUTO_ID, VENDA_ID) values (1.0, 3, 3);

